<?php
/**
 * decrypt_city_data($city_data, $city_data_iv, $secret, $cipher_type = "AES-256-CBC")
 *
 * Decrypts the encrypted data posted by The City to a plugin into an associative array.
 *
 * @param string $city_data     The base64 encoded encrypted data posted by The City (in $_POST['city_data'])
 * @param string $city_data_iv  The base64 encoded encrypted iv posted by The City (in $_POST['city_data_iv'])
 * @param string $secret        The plugin secret generated by The City when the plugin is created
 * @param string $cipher_type   (optional) The cipher to be used to decrypt, AES-256-CBC by default
 *
 * Example
 *
 * $results = decrypt_city_data($_POST['city_data'], $_POST['city_data_iv'], $secret);
 *
 */
function decrypt_city_data($city_data, $city_data_iv, $secret, $cipher_type = "AES-256-CBC")
{
	if(!empty($city_data)) {
		$string_to_decrypt = base64_url_decode($city_data);
		$iv = base64_url_decode($city_data_iv);
		$json_data = openssl_decrypt($string_to_decrypt, $cipher_type, substr($secret, 0, 32), true, $iv);

		return json_decode($json_data, true);
	}

	return '';
}
function base64_url_decode($input)
{
    return base64_decode(strtr($input, '-_,', '+/='));
}
?>